### ISSUE TITLE
Maybe there is issue with Firmware 1.02.004 of the StreamDeck 5x3

### ISSUE THREAD

**Issue by patrick-dmxc** [OpenMacroBoard/StreamDeckSharp#18] opened 2019-11-24 22:23 UTC

**Comment by patrick-dmxc** [comment] 2019-11-24 23:20
Yes after a im searching i found the Problem, this is e newer HArdware-version with a new Product-ID (006D)

**Comment by patrick-dmxc** [comment] 2019-11-25 00:09
I Changed the Pid in the Code, but i think Elgato modifyed their communication

**Comment by wischi-chr** [comment] 2019-11-25 20:39
How did you update your StreamDeck firmware? I can't find the option in the original streamdeck software.

**Comment by patrick-dmxc** [comment] 2019-11-26 13:15
No, a customer got a new StreamDeck wit the Firmware Flashed

**Comment by NoSie** [comment] 2019-11-26 14:05
firmware update should be under preferences (top right icon)

https://raw.githubusercontent.com/bitfocus/companion/master/documentation/images/update.jpg

**Comment by wischi-chr** [comment] 2019-11-26 17:39
![Foo](http://imgur.com/UhpwjV0)

Look like that on my machine

**Comment by patrick-dmxc** [comment] 2019-11-26 20:16
Windows vs. ios

**Comment by wischi-chr** [comment] 2019-11-28 14:33
I don't think it's about Windows vs Mac. The button on the screenshot from @NoSie is visible because there really was a newer firmware available.

Based on:
- a customer got a new StreamDeck with the Firmware flashed
- Elgato confirming that my firmware version is indeed the lasted version for the stream deck
- Change of productId
- Using same protocol as stream deck xl

My guess is that this new stream deck does not only have a new firmware but is in fact a new hardware revision. I asked elgato about that and waiting for feedback.

@patrick-dmxc Thanks for your pull request, but I'm not merging it because duplicating a file and changing a few values would be problematic to maintain in the future. I'm working on a fix right now to support this new device.

**Comment by wischi-chr** [comment] 2019-11-28 17:28
Fixed in version [0.3.5](https://www.nuget.org/packages/StreamDeckSharp/)

**Closed by wischi-chr** 2019-11-28 17:28 UTC

**Comment by patrick-dmxc** [comment] 2019-12-05 01:32
What VS says on Update 
Dependencies can not be resolved. OpenMacroBoard.SDK 0.3.0 is not compatible with StreamDeckSharp 0.3.5 limitation: OpenMacroBoard.SDK (> = 0.4.0 && <1.0.0) .0

**Comment by wischi-chr** [comment] 2019-12-15 07:31
@patrick-dmxc Thanks for reporting that. The issue is currently tracked here: #20 
I'm trying to fix it in the upcomming week.

**Comment by wischi-chr** [comment] 2019-12-31 16:01
@patrick-dmxc Sry it took a while. Should be fixed now, pls let me know if the 1.02.004 stream deck now works as expected.
